package io.github.connortron110.scplockdown.data;

import io.github.connortron110.scplockdown.SCPLockdown;
import io.github.connortron110.scplockdown.api.SCPEntry;
import io.github.connortron110.scplockdown.api.SCPObjectClass;
import io.github.connortron110.scplockdown.client.gui.screen.CardReaderScreen;
import io.github.connortron110.scplockdown.client.gui.screen.inventory.CardWriterScreen;
import io.github.connortron110.scplockdown.data.advancements.LockdownSCPEncounterAdvancements;
import io.github.connortron110.scplockdown.level.SCPDamageTypes;
import io.github.connortron110.scplockdown.level.blockentity.CardReaderBlockEntity;
import io.github.connortron110.scplockdown.level.blocks.CardReaderBlock;
import io.github.connortron110.scplockdown.registration.*;
import io.github.connortron110.scplockdown.registration.holders.StairSlabWallTriple;
import io.github.connortron110.scplockdown.utils.LockdownTextComponents;
import net.minecraft.ChatFormatting;
import net.minecraft.data.PackOutput;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.network.chat.contents.TranslatableContents;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.common.data.LanguageProvider;
import net.minecraftforge.registries.RegistryObject;

public class LockdownLangProvider extends LanguageProvider {

	public LockdownLangProvider(PackOutput output) {
		super(output, SCPLockdown.MOD_ID, "en_us");
	}

	//	TODO: Standardize Lang stuff, as most things are currently all over the place
	@Override
	protected void addTranslations() {
		/*Custom Messages*/
		{
			add(CardReaderScreen.SCREEN_TITLE, "Card Reader");
			add(CardReaderScreen.ADD_MORE_ENTRIES, "ESC to add more entries");
			add(CardReaderScreen.TOOLTIP_EXIT_PROG, "Take the Reader out of programming mode");
			add(CardReaderScreen.TOOLTIP_DELETE_ENTRY, "Delete the selected entry");
			add(CardReaderBlockEntity.CARD_LINKED, "Card linked");
			add(CardReaderBlockEntity.CARD_ALREADY_LINKED, "Card is already linked");
			add(CardReaderBlockEntity.CARD_BLANK, "Card is blank");
			add(CardReaderBlockEntity.ACCESS_DENIED, "Access Denied: Invalid Keycard");
			add(CardReaderBlock.PROGRAMMING_TIP, "Reader must be activated before putting into programming mode");
		}

		/*Misc*/
		{
			add(LockdownTextComponents.BLOCK_INVALID_PLACEMENT, "Invalid placement for Block!");
			add(LockdownTextComponents.BLAST_DOOR_TOO_HIGH, "Blast Door is to High to place!");

			add(LockdownTextComponents.SCREWDRIVER_HAS_TAG, "Screwdriver already has tag!");
			add(LockdownTextComponents.SCREWDRIVER_TAGS_CLEAR, "Cleared Tags from Screwdriver.");
			add(LockdownTextComponents.SCREWDRIVER_TAGS_EMPTY, "Screwdriver has no Tags!");

			add(LockdownTextComponents.SCP023_LOOKED_AT, "Upon witnessing SCP-023 Eyes, you feel a sense of dread. The worst is yet to come...");

			add(LockdownTextComponents.SCP049_SPEECH_1, "Hello.");
			add(LockdownTextComponents.SCP049_SPEECH_2, "Greetings.");
			add(LockdownTextComponents.SCP049_SPEECH_3, "Oh my, yet another victim of the disease...");
			add(LockdownTextComponents.SCP049_SPEECH_4, "You are not a doctor.");
			add(LockdownTextComponents.SCP049_SPEECH_5, "I sense the disease within you.");
			add(LockdownTextComponents.SCP049_SPEECH_6, "I am the cure.");
			add(LockdownTextComponents.SCP049_ATTACKED_1, "Do not be afraid, I am the cure.");
			add(LockdownTextComponents.SCP049_ATTACKED_2, "Stop resisting, I'm here to cure you.");

			add(LockdownTextComponents.SCP902_OPENED, "There was nothing in the strange box");

			add(LockdownTextComponents.SCP914_LINK_REQUIRED, "SCP-914 is missing Input and/or Output door link");
			add(LockdownTextComponents.SCP914_LINK_INPUT, "Now linking Input door to SCP-914");
			add(LockdownTextComponents.SCP914_LINK_OUTPUT, "Now linking Output door to SCP-914");
			add(LockdownTextComponents.SCP914_LINK_SUCCESS, "Door successfully linked to SCP-914");
			add(LockdownTextComponents.SCP914_LINK_EXISTS, "SCP-914 already has linked doors!");
			add(LockdownTextComponents.SCP914_BUSY, "SCP-914 is currently busy.");
		}

		/*Advancements*/
		{
			add(LockdownSCPEncounterAdvancements.SCP_ENCOUNTER_ADVANCEMENT_TITLE, "Secure. Contain. Protect");
			add(LockdownSCPEncounterAdvancements.SCP_ENCOUNTER_ADVANCEMENT_DESC, "Welcome to SCP: Lockdown");

			add(LockdownSCPEncounterAdvancements.SCP148_ADVANCEMENT_TITLE, "Memetic hazards? What are those?");
			add(LockdownSCPEncounterAdvancements.SCP148_ADVANCEMENT_DESC, "Encounter SCP-148");
		}

		/*ToolTips*/
		{
			/*SCP Names*/ //This section is autogenerated only for English
			{
				for (SCPEntry entry : SCPs.entries) {
					add("tooltip.scp" + entry.number + ".name", entry.name);
				}

				for (SCPObjectClass objectClass : SCPObjectClass.values()) {
					add("tooltip.object_class." + objectClass.name.toLowerCase(), objectClass.name);
				}
			}

			add("tooltip.card-reader.0", "Activate Reader then use Screwdriver to program");
			add("tooltip.straight-pipe.0", "Use a Screwdriver in off hand to rotate, (Shift click to change type)");
		}

		/*Death Messages*/
		{
			add("death.attack." + SCPDamageTypes.SCP002CONSUME.location().getPath(), "%1$s was consumed by SCP-002");
			add("death.attack." + SCPDamageTypes.SCP008ZOMBISM.location().getPath(), "%1$s succumbed to SCP-008's infection");
			add("death.attack." + SCPDamageTypes.SCP009FREEZE.location().getPath(), "%1$s got frozen by SCP-009");
			add("death.attack." + SCPDamageTypes.SCP012CURSE.location().getPath(), "%1$s has been affected by SCP-012's curse");
			add("death.attack." + SCPDamageTypes.SCP015DEFENCE.location().getPath(), "%1$s died to SCP-015's aggressive self defence");
			add("death.attack." + SCPDamageTypes.SCP023EXPIRE.location().getPath(), "SCP-023 decided %1$s's time has come");
			add("death.attack." + SCPDamageTypes.SCP035MASK.location().getPath(), "%1$s succumbed to SCP-035's will");
			add("death.attack." + SCPDamageTypes.SCP053HEARTATTACK.location().getPath(), "%1$s had a heart attack trying to harm SCP-053");
			add("death.attack." + SCPDamageTypes.SCP143PETAL.location().getPath(), "%1$s took too many cuts from SCP-143");
			add("death.attack." + SCPDamageTypes.SCP330NOARMS.location().getPath(), "%1$s took too many candies from SCP-330");
			add("death.attack." + SCPDamageTypes.SCP822EXPLODE.location().getPath(), "%1$s got shredded by shrapnel from SCP-822");
			add("death.attack." + SCPDamageTypes.SCP822TOXIN.location().getPath(), "%1$s died from SCP-822's toxin");
		}

		/*Effects*/
		{
			add(SCPEffects.SCP008_ZOMBISM.get(), "Zombism");
			add(SCPEffects.SCP023_CURSE.get(), "SCP-023 Curse");
			add(SCPEffects.SCP027_VERMIN.get(), "Vermin God");
			add(SCPEffects.SCP330_NOARMS.get(), "SCP-330 No Arms");
			add(SCPEffects.SCP822_TOXIN.get(), "SCP-822 Toxin");
		}

		/*SCPs*/
		{ //TODO Auto gen for things that have ISCPData
			/*SCP Names*/
			{
			}
		}

		/*Entities*/
		{
			//addEntity(SCPEntities.DCLASS, "DClass");
			//addEntity(SCPEntities.SCIENTIST, "Scientist");
			addEntity(SCPEntities.GUARD, "Guard");

			addEntity(SCPEntities.MOUSE, "Mouse");
			addEntity(SCPEntities.RAT, "Rat");

			//addEntity(SCPEntities.SCP008_PLAYER, "SCP-008-1 Player");
			//addEntity(SCPEntities.SCP008_GENERIC, "SCP-008-1 Generic");
			//addEntity(SCPEntities.SCP008_DCLASS, "SCP-008-1 DClass");
			//addEntity(SCPEntities.SCP008_SCIENTIST, "SCP-008-1 Scientist");
			addEntity(SCPEntities.SCP008_GUARD, "SCP-008-1 Guard");
			//addEntity(SCPEntities.SCP008_VILLAGER, "SCP-008-1 Villager");
			//addEntity(SCPEntities.SCP008_ILLAGER, "SCP-008-1 Illager");
			//008 Witch
			//addEntity(SCPEntities.SCP008_ENDERMAN, "SCP-008-1 Enderman");
			//addEntity(SCPEntities.SCP008_PIGLIN, "SCP-008-1 Piglin");
			//addEntity(SCPEntities.SCP008_PIGLIN_BRUTE, "SCP-008-1 Piglin Brute");
			//008 Infected 682

			addEntity(SCPEntities.SCP019, "SCP-019-2 Monster");

			addEntity(SCPEntities.SCP023, "SCP-023 Black Shuck");

			//addEntity(SCPEntities.SCP027, "SCP-027 The Vermin God");

			//addEntity(SCPEntities.SCP035_VICTIM, "SCP-035-1");

			addEntity(SCPEntities.SCP049, "SCP-049 Plague Doctor");
			addEntity(SCPEntities.SCP049_PLAYER, "SCP-049-2 Player");

			//addEntity(SCPEntities.SCP053, "SCP-053 Young Girl");

			addEntity(SCPEntities.SCP939, "SCP-939 With Many Voices");
		}

		/*Items*/
		{
			add(SCPItems.SCREWDRIVER, "Screwdriver");

			add(SCPItems.SCP500, "SCP-500 (WIP)");
			add(SCPItems.SCP063, "SCP-063 (WIP)");
			add(SCPItems.SCP109, "SCP-109 (WIP)");

			add(SCPItems.ASH, "Ash");

			add(SCPItems.BURNT_BONE, "Burnt Bone");

			add(SCPItems.CARD_WRITER, "Card Writer");
			add(SCPItems.KEYCARD, "Blank Keycard");
			add("keycard.default.level.1", "Keycard Level 1");
			add("keycard.default.level.2", "Keycard Level 2");
			add("keycard.default.level.3", "Keycard Level 3");
			add("keycard.default.level.4", "Keycard Level 4");
			add("keycard.default.level.5", "Keycard Level 5");

			add(SCPItems.PIZZA, "Pizza");
			add(SCPItems.RED_CANDY, "Red Candy");
			add(SCPItems.ORANGE_CANDY, "Orange Candy");
			add(SCPItems.YELLOW_CANDY, "Yellow Candy");
			add(SCPItems.GREEN_CANDY, "Green Candy");
			add(SCPItems.BLUE_CANDY, "Blue Candy");
			add(SCPItems.PURPLE_CANDY, "Purple Candy");

			add(SCPItems.RODENT_TAIL, "Rodent Tail");

			add(SCPItems.VIAL.asItem().getDescriptionId() + ".empty", "Empty Vial");
			add(SCPItems.VIAL.asItem().getDescriptionId() + ".scp008", "Vial of SCP-008");

			add(SCPItems.SYRINGE.asItem().getDescriptionId() + ".empty", "Empty Syringe");
			add(SCPItems.SYRINGE.asItem().getDescriptionId() + ".scp008", "Syringe of SCP-008");

			add(SCPItems.PUTRID_FLESH, "Putrid Flesh");

			add(SCPItems.SCP005, "SCP-005");

			//add(SCPFluids.SCP006_FOUNTAIN.getBucket(), "SCP-006 Bucket");

			add(SCPItems.SCP035_MASK, "SCP-035 Mask (WIP)");

			add(SCPItems.SCP143_PETALS, "SCP-143 Petals");
			add(SCPItems.SCP143_PROCESSED_LOG, "SCP-143 Processed Log");
			add(SCPItems.SCP143_INGOT, "SCP-143 Ingot");
			add(SCPItems.SCP143_SWORD, "SCP-143 Sword");
			add(SCPItems.SCP143_AXE, "SCP-143 Axe");
			add(SCPItems.SCP143_PICKAXE, "SCP-143 Pickaxe");
			add(SCPItems.SCP143_SHOVEL, "SCP-143 Shovel");
			add(SCPItems.SCP143_HOE, "SCP-143 Hoe");
			add(SCPItems.SCP143_HELMET, "SCP-143 Helmet");
			add(SCPItems.SCP143_CHESTPLATE, "SCP-143 Chestplate");
			add(SCPItems.SCP143_LEGGINGS, "SCP-143 Leggings");
			add(SCPItems.SCP143_BOOTS, "SCP-143 Boots");

			add(SCPItems.SCP148_INGOT, "SCP-148 Ingot");
			add(SCPItems.SCP148_SWORD, "SCP-148 Sword");
			add(SCPItems.SCP148_AXE, "SCP-148 Axe");
			add(SCPItems.SCP148_PICKAXE, "SCP-148 Pickaxe");
			add(SCPItems.SCP148_SHOVEL, "SCP-148 Shovel");
			add(SCPItems.SCP148_HOE, "SCP-148 Hoe");
			add(SCPItems.SCP148_HELMET, "SCP-148 Helmet");
		}

		/*Blocks*/
		{
			add(SCPBlocks.SCP002_METAL, "SCP-002 Metal");
			add(SCPBlocks.SCP002_FLESH_A, "SCP-002 Flesh A");
			add(SCPBlocks.SCP002_FLESH_B, "SCP-002 Flesh B");
			add(SCPBlocks.SCP002_FLESH_C, "SCP-002 Flesh C");
			add(SCPBlocks.SCP002_FLESH_D, "SCP-002 Flesh D");
			add(SCPBlocks.SCP002_COFFEE_TABLE, "SCP-002 Coffee Table");
			add(SCPBlocks.SCP002_PLANT_POT, "SCP-002 Plant Pot");
			add(SCPBlocks.SCP002_TV, "SCP-002 TV");
			add(SCPBlocks.SCP002_DOOR, "SCP-002 Door");
			add(SCPBlocks.SCP002_LAMP, "SCP-002 Lamp");
			add(SCPBlocks.SCP002_ARM_CHAIR, "SCP-002 Arm Chair");
			add(SCPBlocks.SCP002_TABLE, "SCP-002 Table");

			add(SCPBlocks.SCP009, "SCP-009");

			add(SCPBlocks.SCP012, "SCP-012");

			add(SCPBlocks.SCP015_PIPE, "SCP-015 Pipe");
			add(SCPBlocks.SCP015_BLOCK, "SCP-015 Block");

			add(SCPBlocks.SCP019, "SCP-019 Pot");

			add(SCPBlocks.SCP035_GLASS_CASE, "SCP-035 Glass Containment Box (WIP)");

			add(SCPBlocks.SCP124, "SCP-124");

			add(SCPBlocks.SCP143_LOG, "SCP-143 Log");
			add(SCPBlocks.SCP143_LEAVES, "SCP-143 Leaves");
			add(SCPBlocks.SCP143_PLANKS, "SCP-143 Planks");
			add(SCPBlocks.SCP143_SAPLING, "SCP-143 Sapling");

			add(SCPBlocks.SCP148_ORE, "SCP-148 Ore");
			add(SCPBlocks.SCP148_BLOCK, "SCP-148 Block");

			add(SCPBlocks.SCP330, "SCP-330 Bowl");

			add(SCPBlocks.SCP458, "SCP-458 Box");

			add(SCPBlocks.SCP822, "SCP-822");

			add(SCPBlocks.SCP902, "SCP-902");

			//Functional Blocks\\

			add(SCPBlocks.CARD_READER, "Keycard Reader");
			add(SCPBlocks.HEAVY_BUTTON, "Heavy Button");
			add(SCPBlocks.TOILET, "Toilet");
			add(SCPBlocks.CHAIR, "Chair");
			add(SCPBlocks.OFFICE_CHAIR, "Office Chair");
			add(SCPBlocks.TABLE, "Table");
			add(SCPBlocks.OPAQUE_TRAPDOOR, "Opaque Trapdoor");
			add(SCPBlocks.CEILING_LAMP, "Ceiling Lamp");
			add(SCPBlocks.SMALL_LAMP, "Small Lamp");
			add(SCPBlocks.CEILING_LIGHT, "Ceiling Light");

			add(SCPBlocks.WOOD_CRATE, "Wood Crate");
			add(SCPBlocks.DARK_WOOD_CRATE, "Dark Wood Crate");

			add(SCPBlocks.PERSONAL_COMPUTER, "Personal Computer");
			add(SCPBlocks.COMPUTER, "Computer");

			add(SCPBlocks.LOCKER, "Locker");
			add(SCPBlocks.LOCKER.get().getDescriptionId() + ".green", "Locker Green");
			add(SCPBlocks.LOCKER.get().getDescriptionId() + ".lime", "Locker Lime");
			add(SCPBlocks.LOCKER.get().getDescriptionId() + ".rust", "Locker Rust");
			add(SCPBlocks.LOCKER.get().getDescriptionId() + ".white", "Locker White");

			add(SCPBlocks.CONTAINMENT_DOOR, "Containment Door");
			add(SCPBlocks.SLIDING_DOOR, "Sliding Door");
			add(SCPBlocks.MAGNETIZED_DOOR, "Magnetized Door");
			add(SCPBlocks.BLAST_DOOR, "Blast Door");

			//Normal Blocks\\

			add(SCPBlocks.CEILING, "Ceiling");
			add(SCPBlocks.CEILING_TILE, "Ceiling Tile");
			add(SCPBlocks.CEILING_GRATE, "Ceiling Grate");

			add(SCPBlocks.CONTAINMENT_FLOOR, "Containment Floor");
			add(SCPBlocks.FLOOR_A, "Floor A");
			add(SCPBlocks.FLOOR_B, "Floor B");
			add(SCPBlocks.MESH_FLOOR, "Mesh Floor");

			add(SCPBlocks.PLASTER_WALL, "Plaster Wall");
			add(SCPBlocks.VENT, "Vent");
			add(SCPBlocks.VENTILATION, "Ventilation");

			add(SCPBlocks.WALL_A, "Wall A");
			add(SCPBlocks.WALL_B, "Wall B");
			add(SCPBlocks.WALL_C, "Wall C");
			add(SCPBlocks.WALL_D, "Wall D");
			add(SCPBlocks.WALL_E, "Wall E");
			add(SCPBlocks.WALL_F, "Wall F");
			add(SCPBlocks.WALL_G, "Wall G");

			add(SCPBlocks.WHITE_WALL, "White Wall");
			add(SCPBlocks.OLD_WHITE_WALL, "Old White Wall");

			add(SCPBlocks.REINFORCED_IRON, "Reinforced Iron");
			add(SCPBlocks.STEEL, "Steel");
			add(SCPBlocks.REINFORCED_WALL_A, "Reinforced Wall A");
			add(SCPBlocks.REINFORCED_WALL_B, "Reinforced Wall B");
			add(SCPBlocks.REINFORCED_WALL_C, "Reinforced Wall C");

			add(SCPBlocks.EXTERIOR_BOTTOM, "Exterior Bottom");
			add(SCPBlocks.EXTERIOR_MIDDLE, "Exterior Middle");
			add(SCPBlocks.EXTERIOR_TOP, "Exterior Top");

			add(SCPBlocks.MEDICAL_BOTTOM, "Medical Bottom");
			add(SCPBlocks.MEDICAL_TOP, "Medical Top");

			add(SCPBlocks.OFFICE_BOTTOM, "Office Bottom");
			add(SCPBlocks.OFFICE_TOP, "Office Top");

			add(SCPBlocks.PIPE_WALL, "Pipe Wall");

			add(SCPBlocks.SUBLEVEL_WALL_A, "Sublevel Wall A");
			add(SCPBlocks.SUBLEVEL_WALL_B, "Sublevel Wall B");
			add(SCPBlocks.SUBLEVEL_WALL_C, "Sublevel Wall C");
			add(SCPBlocks.REINFORCED_SUBLEVEL_WALL_A, "Reinforced Sublevel Wall A");
			add(SCPBlocks.REINFORCED_SUBLEVEL_WALL_B, "Reinforced Sublevel Wall B");
			add(SCPBlocks.REINFORCED_SUBLEVEL_WALL_C, "Reinforced Sublevel Wall C");
			add(SCPBlocks.METAL_SUBLEVEL, "Metal Sublevel");

			add(SCPBlocks.GRATE, "Grate");
			add(SCPBlocks.BLAST_RESISTANT_GLASS, "Blast Resistant Glass");

			add(SCPBlocks.ARMORY_BOTTOM_A, "Armory Bottom A");
			add(SCPBlocks.ARMORY_TOP_A, "Armory Top A");
			add(SCPBlocks.ARMORY_BOTTOM_B, "Armory Bottom B");
			add(SCPBlocks.ARMORY_TOP_B, "Armory Top B");

			add(SCPBlocks.LABORATORY_BOTTOM_A, "Laboratory Bottom A");
			add(SCPBlocks.LABORATORY_TOP_A, "Laboratory Top A");
			add(SCPBlocks.LABORATORY_BOTTOM_B, "Laboratory Bottom B");
			add(SCPBlocks.LABORATORY_TOP_B, "Laboratory Top B");

			add(SCPBlocks.METAL_PANEL_A, "Metal Panel A");
			add(SCPBlocks.METAL_PANEL_B, "Metal Panel B");
			add(SCPBlocks.METAL_PANEL_C, "Metal Panel C");

			add(SCPBlocks.REINFORCED_GRANITE, "Reinforced Granite");
			add(SCPBlocks.REINFORCED_QUARTZ, "Reinforced Quartz");

			add(SCPBlocks.GREEN_PANEL_A, "Green Panel A");
			add(SCPBlocks.GREEN_PANEL_B, "Green Panel B");
			add(SCPBlocks.GREEN_PANEL_C, "Green Panel C");
			add(SCPBlocks.GREEN_PANEL_D, "Green Panel D");

			add(SCPBlocks.METAL_FLOOR_A, "Metal Floor A");
			add(SCPBlocks.METAL_FLOOR_B, "Metal Floor B");

			add(SCPBlocks.METAL_WALL_A, "Metal Wall A");
			add(SCPBlocks.METAL_WALL_B, "Metal Wall B");

			add(SCPBlocks.STEEL_FLOOR, "Steel Floor");

			add(SCPBlocks.HAZARD, "Hazard");

			addStairSlabWallTriple(SCPBlocks.REINFORCED_IRON_STAIR_SLAB_WALL_TRIPLE, "Reinforced Iron");
			addStairSlabWallTriple(SCPBlocks.STEEL_STAIR_SLAB_WALL_TRIPLE, "Steel");
			addStairSlabWallTriple(SCPBlocks.SUBLEVEL_STAIR_SLAB_WALL_TRIPLE, "Sublevel");
			addStairSlabWallTriple(SCPBlocks.REINFORCED_SUBLEVEL_STAIR_SLAB_WALL_TRIPLE, "Reinforced Sublevel");
			addStairSlabWallTriple(SCPBlocks.METAL_SUBLEVEL_STAIR_SLAB_WALL_TRIPLE, "Metal Sublevel");
			addStairSlabWallTriple(SCPBlocks.METAL_WALL_A_SUBLEVEL_STAIR_SLAB_WALL_TRIPLE, "Metal Wall A");

			add(SCPBlocks.WALL_STAIRS, "Wall Stairs");
			add(SCPBlocks.FLOOR_A_STAIRS, "Floor A Stairs");
			add(SCPBlocks.FLOOR_B_STAIRS, "Floor B Stairs");
			add(SCPBlocks.WHITE_STAIRS, "White Stairs");
			add(SCPBlocks.REINFORCED_WALL_A_STAIRS, "Reinforced Wall A Stairs");
			add(SCPBlocks.REINFORCED_WALL_B_STAIRS, "Reinforced Wall B Stairs");
			add(SCPBlocks.REINFORCED_WALL_C_STAIRS, "Reinforced Wall C Stairs");

			add(SCPBlocks.WALL_SLAB, "Wall Slab");
			add(SCPBlocks.FLOOR_A_SLAB, "Floor A Slab");
			add(SCPBlocks.FLOOR_B_SLAB, "Floor B Slab");
			add(SCPBlocks.WHITE_SLAB, "White Slab");
			add(SCPBlocks.REINFORCED_WALL_A_SLAB, "Reinforced Wall A Slab");
			add(SCPBlocks.REINFORCED_WALL_B_SLAB, "Reinforced Wall B Slab");
			add(SCPBlocks.REINFORCED_WALL_C_SLAB, "Reinforced Wall C Slab");

			add(SCPBlocks.REINFORCED_WALL_C_WALL, "Reinforced Wall C Wall");
			add(SCPBlocks.EXTERIOR_BOTTOM_WALL, "Exterior Bottom Wall");
			add(SCPBlocks.EXTERIOR_MIDDLE_WALL, "Exterior Middle Wall");
			add(SCPBlocks.EXTERIOR_TOP_WALL, "Exterior Top Wall");
			add(SCPBlocks.QUARTZ_WALL, "Quartz Wall");
			add(SCPBlocks.PIPE_WALL_WALL, "Pipe Wall Wall");
			add(SCPBlocks.METAL_WALL_B_WALL, "Metal Wall B Wall");
			add(SCPBlocks.SMOOTH_QUARTZ_WALL, "Smooth Quartz Wall");

			SCPBlocks.STRAIGHT_PIPES.getPairs().forEach(pair -> add(pair.getRegistryObject(), "Straight Pipe " + pair.getColor().getDisplayName()));
			SCPBlocks.CORNER_PIPES.getPairs().forEach(pair -> add(pair.getRegistryObject(), "Corner Pipe " + pair.getColor().getDisplayName()));
			SCPBlocks.JUNC3_PIPES.getPairs().forEach(pair -> add(pair.getRegistryObject(), "3 Junction Pipe " + pair.getColor().getDisplayName()));
			SCPBlocks.TJUNC_PIPES.getPairs().forEach(pair -> add(pair.getRegistryObject(), "T Junction Pipe " + pair.getColor().getDisplayName()));
			SCPBlocks.JUNC4X_PIPES.getPairs().forEach(pair -> add(pair.getRegistryObject(), "4 X Junction Pipe " + pair.getColor().getDisplayName()));
			SCPBlocks.JUNC4_PIPES.getPairs().forEach(pair -> add(pair.getRegistryObject(), "4 Junction Pipe " + pair.getColor().getDisplayName()));
			SCPBlocks.JUNC5_PIPES.getPairs().forEach(pair -> add(pair.getRegistryObject(), "5 Junction Pipe " + pair.getColor().getDisplayName()));
			SCPBlocks.JUNC6_PIPES.getPairs().forEach(pair -> add(pair.getRegistryObject(), "6 Junction Pipe " + pair.getColor().getDisplayName()));

			//Vanilla Extended Building Blocks
			add(SCPBlocks.SMOOTH_STONE_STAIRS, "Smooth Stone Stairs");

			addStairSlabWallTriple(SCPBlocks.WHITE_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "White Terracotta");
			addStairSlabWallTriple(SCPBlocks.ORANGE_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Orange Terracotta");
			addStairSlabWallTriple(SCPBlocks.MAGENTA_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Magenta Terracotta");
			addStairSlabWallTriple(SCPBlocks.LIGHT_BLUE_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Light Blue Terracotta");
			addStairSlabWallTriple(SCPBlocks.YELLOW_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Yellow Terracotta");
			addStairSlabWallTriple(SCPBlocks.LIME_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Lime Terracotta");
			addStairSlabWallTriple(SCPBlocks.PINK_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Pink Terracotta");
			addStairSlabWallTriple(SCPBlocks.GRAY_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Gray Terracotta");
			addStairSlabWallTriple(SCPBlocks.LIGHT_GRAY_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Light Gray Terracotta");
			addStairSlabWallTriple(SCPBlocks.CYAN_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Cyan Terracotta");
			addStairSlabWallTriple(SCPBlocks.PURPLE_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Purple Terracotta");
			addStairSlabWallTriple(SCPBlocks.BLUE_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Blue Terracotta");
			addStairSlabWallTriple(SCPBlocks.BROWN_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Brown Terracotta");
			addStairSlabWallTriple(SCPBlocks.GREEN_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Green Terracotta");
			addStairSlabWallTriple(SCPBlocks.RED_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Red Terracotta");
			addStairSlabWallTriple(SCPBlocks.BLACK_TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Black Terracotta");
			addStairSlabWallTriple(SCPBlocks.TERRACOTTA_STAIR_SLAB_WALL_TRIPLE, "Terracotta");


			add(SCPBlocks.STONE_WALL, "Stone Wall");
			add(SCPBlocks.POLISHED_GRANITE_WALL, "Polished Granite Wall");
			add(SCPBlocks.POLISHED_DIORITE_WALL, "Polished Diorite Wall");
			add(SCPBlocks.POLISHED_ANDESITE_WALL, "Polished Andesite Wall");
		}

		/*GUIs / Screens*/
		{
			add("screen.computer.url", "URL");
			add("screen.computer.display", "Display String");

			add("scplockdown.gui.menu.cardwriter", "Card Writer");
			add(CardWriterScreen.BUTTON_INSERT_CARD, "Insert Card");
			add(CardWriterScreen.BUTTON_NAME_REQUIRED, "Name Required");
			add(CardWriterScreen.BUTTON_COLOUR_REQUIRED, "Colour Required");
			add(CardWriterScreen.BUTTON_COLOUR_INVALID, "Colour Invalid");
			add(CardWriterScreen.BUTTON_KEY_REQUIRED, "Key Required");
			add(CardWriterScreen.BUTTON_CONFIGURE, "Configure Card");
			add(CardWriterScreen.NAME_SUGGESTION, "Keycard Name");
			add(CardWriterScreen.KEY_SUGGESTION, "No Real Passwords");
			add(CardWriterScreen.CARD_NAME, "Name:");
			add(CardWriterScreen.CARD_COLOUR, "Colour:");
			add(CardWriterScreen.CARD_KEY, "Key:");
		}

		/*Containers*/
		{
			add("container.crate", "Crate");
			add("container.locker", "Locker");
		}

		/*Item Groups*/
		{
			add("itemGroup.lockdown_items", "SCP: Lockdown Items");
			//add("itemGroup.lockdown_functional_blocks", "SCP: Lockdown Functional Blocks");
			add("itemGroup.lockdown_building_blocks", "SCP: Lockdown Building Blocks");
			add("itemGroup.lockdown_functional_blocks", "SCP: Lockdown Functional Blocks");
			//add("itemGroup.lockdown_documents", "SCP: Lockdown Documents");
			add("itemGroup.lockdown_entities", "SCP: Lockdown Entities");
		}

        /*
        //Misc SCPs Auto Gen things
        SCPs.getSCPs().forEach(entry -> {
            add(SCPItems.TOKEN.get().getDescriptionId() + "_" + entry.getRegistryName(), "Token " + entry.getNumber());
            add(SCPItems.LABEL_BLOCK_ITEM.get().getDescriptionId() + "_" + entry.getRegistryName(), "(WIP) Label " + entry.getNumber());
        });

        SCPBlocks.BLOCKS.getEntries().forEach(blockRegistryObject -> {
            Block block = blockRegistryObject.get();
            try {

                Field data = LanguageProvider.class.getDeclaredField("data");
                data.setAccessible(true);

                if (generatedLangProvider.containsKey(block.getDescriptionId())) {
                    if (generatedLangProvider.get(block.getDescriptionId()) != null) { //Intentional to say this doesn't need a name, doubt it will happen but its here anyways
                        if (!((Map<String, String>) data.get(this)).containsKey(block.getDescriptionId())) {
                            add(block.getDescriptionId(), generatedLangProvider.get(block.getDescriptionId()));
                        }
                    }
                } else {
                    //If generatedLangProvider doesn't contain this blocks key we move to automatically make its name! (can be a bit broken but that's why we have generatedLangProvider)
                    //Gen Lang goes off the registry name
                    String[] s = block.getRegistryName().getPath().split("_");
                    StringBuilder lang = null;
                    for (String str : s) {
                        String result = str.substring(0, 1).toUpperCase() + str.substring(1);
                        if (lang == null) lang = new StringBuilder(result);
                        else lang.append(" ").append(result);
                    }
                    if (lang != null) {
                        if (!((Map<String, String>) data.get(this)).containsKey(block.getDescriptionId())) {
                            add(block.getDescriptionId(), lang.toString());
                        }
                    }
                }
            } catch (NoSuchFieldException | IllegalAccessException e) {
                e.printStackTrace();
            }
        });

         */
	}

	protected void addStairSlabWallTriple(StairSlabWallTriple stairSlabWall, String baseName) {
		add(stairSlabWall.getStairs(), baseName + " Stairs");
		add(stairSlabWall.getSlab(), baseName + " Slab");
		add(stairSlabWall.getWall(), baseName + " Wall");
	}

	private void add(Component component, String s) {
		add(((TranslatableContents) component.getContents()).getKey(), s);
	}

	private void add(ItemLike entry, String s) {
		add(entry.asItem(), s);
	}

	private <T extends RegistryObject<?>> void add(T entry, String s) {
		if (entry.get() instanceof Block) add((Block) entry.get(), s);
		else if (entry.get() instanceof Item) add((Item) entry.get(), s);
		else throw new IllegalArgumentException("Unknown entry type: " + entry);
	}

	/**
	 * Gives an entity and its egg (if it exists) the provided name
	 */
	private <E extends Entity> void addEntity(RegistryObject<EntityType<E>> entry, String s) {
		add(entry.get(), s);
		if (SCPEntities.getEggFromEntity(entry) != null) {
			add(SCPEntities.getEggFromEntity(entry).asItem(), s + " Spawn Egg");
		}
	}

	private void makeToolTipLang(String number, String s) {
		add("scp." + number + ".description", "§8" + s);
	}

	public static MutableComponent createToolTipLang(String number) {
		return Component.translatable("scp." + number + ".description");
	}
}
